---
services:
  teambuilder-postgres:
    image: postgres:17.3-alpine
    container_name: teambuilder-postgres
    environment:
      POSTGRES_DB: groupforge
      POSTGRES_USER: groupforgeUser
      POSTGRES_PASSWORD: GroupForgeSoftware1234!
    ports:
      - 5432:5432
    restart: unless-stopped
